[package]
name = "tile-map-generator"
version = "0.1.0"
authors = ["Micah Tigley <tigleym@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.2"
rand = "0.7.3"
ron = "*"
serde = "1.0.105"
